alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias h="history"
alias q='exit'
alias c='clear'
alias md='mkdir'
alias rm='rm -rf'
alias s="source"
alias n='nano'
alias cm='chmod +x'
alias g='git'
alias gc='git clone'
alias push="git pull && git add . && git commit -m 'mobile push' && git push"
alias ohmyzsh='nano $HOME/.oh-my-zsh'
alias setalias='nano $HOME/.oh-my-zsh/custom/aliases.zsh'
alias getalias='cat $HOME/.oh-my-zsh/custom/aliases.zsh'