alias setalias='nano $HOME/.oh-my-zsh/custom/aliases.zsh'
alias getalias='bat $HOME/.oh-my-zsh/custom/aliases.zsh'
alias ..='cd ..'
alias q='exit'
alias c='clear'
alias md='mkdir'
alias s="source"
alias n='nano'
alias cm='chmod +x'
alias clone='git clone'
alias push="git pull && git add . && git commit -m 'mobile push' && git push"
alias zshconfig='nano ~/.zshrc'
alias ohmyzsh='nano ~/.oh-my-zsh'
